name: github_auto_cloner
description: A command-line application to auto clone github repo from specified username
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.12.2
  process_run: ^0.11.2+8

dev_dependencies:
  pedantic: ^1.9.0
